// Generated by `swift package generate-relief-codes`. Do not edit by hand.
// Source: Sources/TaxKit/Resources/Rules/*.json

extension ReliefCode {

    public static let lifestyle = ReliefCode("LIFESTYLE")
    public static let medicalSerious = ReliefCode("MEDICAL_SERIOUS")

    /// Every code declared in the shipped rulebooks, in sorted raw-value order.
    public static let allGenerated: [ReliefCode] = [
        .lifestyle,
        .medicalSerious,
    ]
}
