// Generated by `swift package generate-relief-codes`. Do not edit by hand.
// Source: Sources/TaxKit/Resources/Rules/*.json

extension ReliefCode {

    public static let breastfeeding = ReliefCode("BREASTFEEDING")
    public static let childcare = ReliefCode("CHILDCARE")
    public static let childDisabled = ReliefCode("CHILD_DISABLED")
    public static let childDisabledTertiary = ReliefCode("CHILD_DISABLED_TERTIARY")
    public static let childPreTertiary = ReliefCode("CHILD_PRE_TERTIARY")
    public static let childTertiary = ReliefCode("CHILD_TERTIARY")
    public static let childUnder18 = ReliefCode("CHILD_UNDER_18")
    public static let disabledEquipment = ReliefCode("DISABLED_EQUIPMENT")
    public static let disabledSelf = ReliefCode("DISABLED_SELF")
    public static let disabledSpouse = ReliefCode("DISABLED_SPOUSE")
    public static let educationSelf = ReliefCode("EDUCATION_SELF")
    public static let educationUpskill = ReliefCode("EDUCATION_UPSKILL")
    public static let epfContribution = ReliefCode("EPF_CONTRIBUTION")
    public static let evCharging = ReliefCode("EV_CHARGING")
    public static let housingLoanInterest = ReliefCode("HOUSING_LOAN_INTEREST")
    public static let insuranceEduMedical = ReliefCode("INSURANCE_EDU_MEDICAL")
    public static let insuranceLifeEpf = ReliefCode("INSURANCE_LIFE_EPF")
    public static let lifestyle = ReliefCode("LIFESTYLE")
    public static let lifestyleSports = ReliefCode("LIFESTYLE_SPORTS")
    public static let lifeInsurance = ReliefCode("LIFE_INSURANCE")
    public static let medicalCheckup = ReliefCode("MEDICAL_CHECKUP")
    public static let medicalDental = ReliefCode("MEDICAL_DENTAL")
    public static let medicalLearndis = ReliefCode("MEDICAL_LEARNDIS")
    public static let medicalSerious = ReliefCode("MEDICAL_SERIOUS")
    public static let medicalVaccination = ReliefCode("MEDICAL_VACCINATION")
    public static let parentsCheckup = ReliefCode("PARENTS_CHECKUP")
    public static let parentsMedical = ReliefCode("PARENTS_MEDICAL")
    public static let prsAnnuity = ReliefCode("PRS_ANNUITY")
    public static let selfAndDependents = ReliefCode("SELF_AND_DEPENDENTS")
    public static let socsoEis = ReliefCode("SOCSO_EIS")
    public static let spouseAlimony = ReliefCode("SPOUSE_ALIMONY")
    public static let sspn = ReliefCode("SSPN")

    /// Every code declared in the shipped rulebooks, in sorted raw-value order.
    public static let allGenerated: [ReliefCode] = [
        .breastfeeding,
        .childcare,
        .childDisabled,
        .childDisabledTertiary,
        .childPreTertiary,
        .childTertiary,
        .childUnder18,
        .disabledEquipment,
        .disabledSelf,
        .disabledSpouse,
        .educationSelf,
        .educationUpskill,
        .epfContribution,
        .evCharging,
        .housingLoanInterest,
        .insuranceEduMedical,
        .insuranceLifeEpf,
        .lifestyle,
        .lifestyleSports,
        .lifeInsurance,
        .medicalCheckup,
        .medicalDental,
        .medicalLearndis,
        .medicalSerious,
        .medicalVaccination,
        .parentsCheckup,
        .parentsMedical,
        .prsAnnuity,
        .selfAndDependents,
        .socsoEis,
        .spouseAlimony,
        .sspn,
    ]
}
