import Foundation

// Usage: ReliefCodeGenerator <rules-directory> <output-file>
//
// Reads every ya-*.json, collects the union of relief codes including nested children
// and retired aliases, and writes ReliefCode+Generated.swift.

guard CommandLine.arguments.count == 3 else {
    FileHandle.standardError.write(
        Data("usage: ReliefCodeGenerator <rules-dir> <output-file>\n".utf8))
    exit(2)
}

let rulesDirectory = URL(fileURLWithPath: CommandLine.arguments[1])
let outputFile = URL(fileURLWithPath: CommandLine.arguments[2])

/// Minimal mirrors of the rulebook shape — the generator must not depend on TaxKit,
/// because TaxKit is what it generates into.
struct RawRelief: Decodable {
    let code: String
    let children: [RawRelief]?
}
struct RawRetirement: Decodable {
    let retired: String
}
struct RawRuleSet: Decodable {
    let reliefs: [RawRelief]
    let retiredCodes: [RawRetirement]?
}

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("error: \(message)\n".utf8))
    exit(1)
}

func collect(_ reliefs: [RawRelief], fileName: String, into sources: inout [String: String]) {
    for relief in reliefs {
        if sources[relief.code] == nil { sources[relief.code] = fileName }
        collect(relief.children ?? [], fileName: fileName, into: &sources)
    }
}

/// Maps each collected code to the file it was first seen in, for error messages.
var codeSources: [String: String] = [:]
let files = try FileManager.default
    .contentsOfDirectory(at: rulesDirectory, includingPropertiesForKeys: nil)
    .filter { $0.lastPathComponent.hasPrefix("ya-") && $0.pathExtension == "json" }
    .sorted { $0.lastPathComponent < $1.lastPathComponent }

for file in files {
    let ruleSet = try JSONDecoder().decode(RawRuleSet.self, from: try Data(contentsOf: file))
    collect(ruleSet.reliefs, fileName: file.lastPathComponent, into: &codeSources)
    for retirement in ruleSet.retiredCodes ?? [] {
        if codeSources[retirement.retired] == nil {
            codeSources[retirement.retired] = file.lastPathComponent
        }
    }
}

/// A relief code must be a valid Swift-identifier source: an uppercase ASCII letter
/// followed by any number of uppercase ASCII letters, digits, or underscores.
func isValidCode(_ code: String) -> Bool {
    guard let first = code.unicodeScalars.first, ("A" as Unicode.Scalar)...("Z" as Unicode.Scalar) ~= first else {
        return false
    }
    return code.unicodeScalars.allSatisfy { scalar in
        (("A" as Unicode.Scalar)...("Z" as Unicode.Scalar) ~= scalar)
            || (("0" as Unicode.Scalar)...("9" as Unicode.Scalar) ~= scalar)
            || scalar == "_"
    }
}

// Validate every collected code before generating anything, so a bad rulebook never
// produces a partial file.
for code in codeSources.keys.sorted() {
    guard isValidCode(code) else {
        fail(
            "relief code '\(code)' in \(codeSources[code]!) is not a valid identifier source "
                + "— it must match ^[A-Z][A-Z0-9_]*$"
        )
    }
}

/// Reserved words that would produce an invalid or shadowing Swift declaration if used bare.
let swiftKeywords: Set<String> = [
    "self", "default", "type", "static", "class", "struct", "enum", "protocol", "extension",
    "init", "deinit", "let", "var", "func", "return", "if", "else", "for", "while", "switch",
    "case", "break", "continue", "import", "public", "private", "internal", "open", "where",
    "is", "as", "in", "do", "try", "catch", "throw", "throws", "rethrows", "guard", "defer",
    "repeat", "nil", "true", "false", "super", "Self", "Any", "operator", "subscript",
    "associatedtype", "typealias", "inout", "some", "any",
]

/// LIFESTYLE -> lifestyle, MEDICAL_SERIOUS -> medicalSerious
func rawSwiftIdentifier(for code: String) -> String {
    let parts = code.split(separator: "_").map { $0.lowercased() }
    guard let first = parts.first else { return code.lowercased() }
    return ([first] + parts.dropFirst().map(\.capitalized)).joined()
}

/// Escapes the identifier with backticks when it collides with a Swift keyword.
func swiftIdentifier(for code: String) -> String {
    let raw = rawSwiftIdentifier(for: code)
    return swiftKeywords.contains(raw) ? "`\(raw)`" : raw
}

let sorted = codeSources.keys.sorted()

// Detect two distinct codes mapping to the same Swift identifier before writing anything.
var identifierOwners: [String: String] = [:]
for code in sorted {
    let identifier = rawSwiftIdentifier(for: code)
    if let existing = identifierOwners[identifier] {
        fail(
            "relief codes '\(existing)' and '\(code)' both produce the Swift identifier "
                + "'\(identifier)' — rename one of them in the rulebook"
        )
    }
    identifierOwners[identifier] = code
}

var out = """
// Generated by `swift package generate-relief-codes`. Do not edit by hand.
// Source: Sources/TaxKit/Resources/Rules/*.json

extension ReliefCode {


"""
for code in sorted {
    out += "    public static let \(swiftIdentifier(for: code)) = ReliefCode(\"\(code)\")\n"
}
out += """

    /// Every code declared in the shipped rulebooks, in sorted raw-value order.
    public static let allGenerated: [ReliefCode] = [

"""
for code in sorted {
    out += "        .\(swiftIdentifier(for: code)),\n"
}
out += """
    ]
}

"""

try out.write(to: outputFile, atomically: true, encoding: .utf8)
print("Wrote \(sorted.count) relief codes to \(outputFile.path)")
