import Foundation

// Usage: ReliefCodeGenerator <rules-directory> <output-file>
//
// Reads every ya-*.json, collects the union of relief codes including nested children
// and retired aliases, and writes ReliefCode+Generated.swift.

guard CommandLine.arguments.count == 3 else {
    FileHandle.standardError.write(
        Data("usage: ReliefCodeGenerator <rules-dir> <output-file>\n".utf8))
    exit(2)
}

let rulesDirectory = URL(fileURLWithPath: CommandLine.arguments[1])
let outputFile = URL(fileURLWithPath: CommandLine.arguments[2])

/// Minimal mirrors of the rulebook shape — the generator must not depend on TaxKit,
/// because TaxKit is what it generates into.
struct RawRelief: Decodable {
    let code: String
    let children: [RawRelief]?
}
struct RawRetirement: Decodable {
    let retired: String
}
struct RawRuleSet: Decodable {
    let reliefs: [RawRelief]
    let retiredCodes: [RawRetirement]?
}

func collect(_ reliefs: [RawRelief], into set: inout Set<String>) {
    for relief in reliefs {
        set.insert(relief.code)
        collect(relief.children ?? [], into: &set)
    }
}

var codes: Set<String> = []
let files = try FileManager.default
    .contentsOfDirectory(at: rulesDirectory, includingPropertiesForKeys: nil)
    .filter { $0.lastPathComponent.hasPrefix("ya-") && $0.pathExtension == "json" }
    .sorted { $0.lastPathComponent < $1.lastPathComponent }

for file in files {
    let ruleSet = try JSONDecoder().decode(RawRuleSet.self, from: try Data(contentsOf: file))
    collect(ruleSet.reliefs, into: &codes)
    for retirement in ruleSet.retiredCodes ?? [] { codes.insert(retirement.retired) }
}

/// LIFESTYLE -> lifestyle, MEDICAL_SERIOUS -> medicalSerious
func swiftIdentifier(for code: String) -> String {
    let parts = code.split(separator: "_").map { $0.lowercased() }
    guard let first = parts.first else { return code.lowercased() }
    return ([first] + parts.dropFirst().map(\.capitalized)).joined()
}

let sorted = codes.sorted()
var out = """
// Generated by `swift package generate-relief-codes`. Do not edit by hand.
// Source: Sources/TaxKit/Resources/Rules/*.json

extension ReliefCode {


"""
for code in sorted {
    out += "    public static let \(swiftIdentifier(for: code)) = ReliefCode(\"\(code)\")\n"
}
out += """

    /// Every code declared in the shipped rulebooks, in sorted raw-value order.
    public static let allGenerated: [ReliefCode] = [

"""
for code in sorted {
    out += "        .\(swiftIdentifier(for: code)),\n"
}
out += """
    ]
}

"""

try out.write(to: outputFile, atomically: true, encoding: .utf8)
print("Wrote \(sorted.count) relief codes to \(outputFile.path)")
